In [2]:
import pandas as pd
import numpy as np

In [157]:
class ScoreType:
    def __init__(self, name, condition_function, scoring_function, number = None):
        self.name = name
        self.condition_function = condition_function
        self.scoring_function = scoring_function
        self.number = number

    def check_condition(self, hand, number = None):
        return self.condition_function(hand, number = self.number)
    
    def calculate_score(self, hand, number = None):
        return self.scoring_function(hand, number)

In [181]:
def condition_tops(hand, number):
    return number in hand

def score_tops(hand, number):
    return list(hand).count(number) * number

ones = ScoreType(
    name = 'Twos',
    condition_function = condition_tops,
    scoring_function = score_tops,
    number = 1
)

twos = ScoreType(
    name = 'Twos',
    condition_function = condition_tops,
    scoring_function = score_tops,
    number = 2
)

threes = ScoreType(
    name = 'Twos',
    condition_function = condition_tops,
    scoring_function = score_tops,
    number = 3
)

fours = ScoreType(
    name = 'Twos',
    condition_function = condition_tops,
    scoring_function = score_tops,
    number = 4
)

fives = ScoreType(
    name = 'Twos',
    condition_function = condition_tops,
    scoring_function = score_tops,
    number = 5
)

sixes = ScoreType(
    name = 'Twos',
    condition_function = lambda hand, number: number in hand, # condition_tops,
    scoring_function = lambda hand, number: list(hand).count(number) * number, # score_tops,
    number = 6
)

def condition_three_kind(hand, number):
    unique_counts = np.unique(hand, return_counts = True)[1].max()
    return True if unique_counts.max() >= 3 else False

def score_three_kind(hand, number):
    return hand.sum()

three_kind = ScoreType(
    name = 'Three of a Kind',
    condition_function = condition_three_kind,
    scoring_function = score_three_kind
)

def condition_four_kind(hand, number):
    unique_counts = np.unique(hand, return_counts = True)[1].max()
    return True if unique_counts.max() >= 4 else False

def score_four_kind(hand, number):
    return hand.sum()

four_kind = ScoreType(
    name = 'Four of a Kind',
    condition_function = condition_four_kind,
    scoring_function = score_four_kind
)

In [171]:
three_kind.calculate_score(hand, three_kind.number)

18

In [182]:
score_types = [
    ones,
    twos,
    threes,
    fours,
    fives,
    sixes,
    three_kind,
    four_kind,
    # full_house,
    # small_straight,
    # large_straight,
    # yahtzee,
    # chance
]

In [193]:
for round in range(7):

    hand = np.array([], dtype = int)

    for turn in range(3):

        roll = np.random.randint(1, 7, 5 - len(hand))
        hand = np.append(hand, roll)

        if turn < 2:
            hand = np.random.choice(
                a = hand,
                size = np.random.randint(1,5)
            )

        print(hand)

    remaining_scores = score_types
    have_score = False
    counter = 0

    while have_score == False:
        if counter == len(remaining_scores):
            score = 0
            break
        score_type = score_types[len(remaining_scores)-counter-1]
        if score_type.check_condition(hand, score_type.number):
            score = score_type.calculate_score(hand, score_type.number)
            have_score = True
        else:
            counter += 1

    print(score)

[3 5 3]
[3]
[3 6 5 2 2]
6
[2]
[4 6 2 6]
[4 6 2 6 5]
12
[6 1 6 1]
[6]
[6 4 1 6 1]
12
[5 5 4 4]
[4 4 4 5]
[4 4 4 5 4]
21
[4]
[4]
[4 1 6 5 6]
12
[1]
[6 1 1 5]
[6 1 1 5 2]
6
[2 5 6 2]
[3 3 2]
[3 3 2 6 4]
6
